### PR TITLE
Add Drowned Entity, Vindicator Entity and Evoker Entity

### PR DESCRIPTION
**Pull request by Kaooot**

### CODE REVIEW

**Comment by lukeeey** [comment]
Seriously learn how to use git

**Comment by Kaooot** [comment]
Why is that no matter or not?

**Comment by lukeeey** [comment]
Because it means you dont make a million commits for some simple changes.

**Comment by Kaooot** [comment]
Ah okay i think i will use it! Tank you for your tip 👍

**Comment by lukeeey** [comment]
You didnt have to close it

**Pull request closed without merging**
