### PR TITLE
Add ChatPacket (+ api implementation)

### PR DESCRIPTION
**Pull request by Krymonota**
I added a packet for sending messages (chat, popup and tip) to the client and implemented it into the API.

### CODE REVIEW

**Comment by Krymonota** [comment]
Regarding chat messages: We should consider to move from simple Strings to a custom chat message builder (or something like that). However, it's on a low priority for now.

**Comment by BlackyPaw** [comment]
Please do not use anything other than your username on @author tags; rest looks fine and is ready to be pulled, thank you!

**Comment by Krymonota** [comment]
@BlackyPaw: There you go!

**Comment by BlackyPaw** [comment]
Thank you a lot! Merged.

**Pull request merged**
