### PR TITLE
Let Git ignore junk like .DS_Store or Maven compiled files (drp.xml/t…

### PR DESCRIPTION
**Pull request by ghost**
…arget)

### CODE REVIEW

**Comment by ghost** [comment]
drp.xml basically means dependency-reduced-pom.xml ☺️

**Comment by Janmm14** [comment]
Maybe edit pom to not generate `dependency-reduced-pom.xml` if you're at it - just an idea

**Comment by ghost** [comment]
Not a bad idea 👍

**Comment by severinkehding** [comment]
Do you mind giving some context on why this change is needed? Each plugin should be self sustainable and with that change the lack of the dependency-reduced-pom.xml finding an error would be "harder".

the Gitignore changes are imho a-ok. @geNAZt  what do you think?

**Review by geNAZt — APPROVED** [review]

**Review by severinkehding — APPROVED** [review]
after talking with geNAZt those changes do look good and they make sense

**Pull request merged**
