### PR TITLE
Add getFallDistance to API

### PR DESCRIPTION
**Pull request by LucGamesYT**

### CODE REVIEW

**Comment by lukeeey** [comment]
This doesnt work unless you override the method in the class?

**Comment by Janmm14** [comment]
I guess the implementation already has this method.

**Comment by lukeeey** [comment]
But if it doesn't override it then it wouldn't work? And if it did override it before then that would be an error because the method it was overriding didn't exist until this PR.

**Comment by lukeeey** [comment]
Just checked, this method is not in the Entity class in `gomint-server` and therefore this PR is completely useless.

**Comment by lukeeey** [comment]
Nevermind i have been defeated by lombok lmao

**Comment by LucGamesYT** [comment]
Here is the Getter in gomint-server 
https://github.com/GoMint/GoMint/blob/master/gomint-server/src/main/java/io/gomint/server/entity/Entity.java#L113

**Comment by LucGamesYT** [comment]
The getFallDistance method works for me

**Pull request merged**
