### PR TITLE
Fix plugin threads not returning correct plugin class

### PR DESCRIPTION
**Pull request by geNAZt**

### CODE REVIEW

**Review by Soupertonic — APPROVED** [review]

**Comment by lukeeey** [comment]
Why do you make a pull request for every commit? I think you’re getting carried away with bots and GitHub actions lol.

**Comment by geNAZt** [comment]
No, this is how the workflow works

**Comment by lukeeey** [comment]
What’s the benefit?

**Comment by Janmm14** [comment]
Someone else is looking over the change always.

**Pull request merged**
