### PR TITLE
Implement all burn times

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lukeeey** [comment]
Shouldn't the method be in gomint-server like all the other values? Also, why so many commits :tongue:

**Comment by ghost** [comment]
Those commits can be squashed. ;)
I dunno. The burn times are general purpose which means there's actually no reason for other implementations of GoMint to implement them all over again

**Comment by lukeeey** [comment]
That still doesnt explain why they are in the interface instead of in the implementation class. I think if you were to put it there you might as well move other stuff, such as break time, to the api as well (not that it even needs to be there)

**Comment by Janmm14** [comment]
My opinion is similar to @lukeeey's

**Comment by ghost** [comment]
I had to get another opinion lol

**Comment by ghost** [comment]
Fine then. Moving everything to the implementation classes

**Comment by DelxHQ** [comment]
Half a dozen commits on the way then

**Comment by ghost** [comment]
Actually not. It is going to be just one commit

**Comment by ghost** [comment]
Aight. All the default implementations have been moved to their actual implementation class

**Pull request merged**
