### PR TITLE
Don't make the players wonder who kicked them.

### PR DESCRIPTION
**Pull request by ghost**
new kick message

### CODE REVIEW

**Review by DelxHQ — COMMENTED** [review]
Old code style needs to be stripped out.

**Review by DelxHQ — COMMENTED** [review]
Keep the messages vanilla

**Comment by ghost** [comment]
Kick isn't a vanilla command though?

**Comment by DelxHQ** [comment]
Well something like spigot. Not every server owner will like seeing who the player got kicked by

**Comment by ghost** [comment]
For what reason? This would prevent abuse since it'll show who kicked them /;

_or make something that will allow users to edit the messages without modifying gomint internally_

**Comment by geNAZt** [comment]
Rebase please (there are merge conflicts due to the new NPE check)

**Comment by Janmm14** [comment]
Does the log show disconnect messages? If not, add a separate log output please.

**Comment by dktapps** [comment]
You should consider making it more extensible instead of changing hardcoded behaviour the way you want it. Just my two cents.

**Comment by geNAZt** [comment]
The command System allows overriding of all commands. So even if the kicking player/console should not be listed to the player getting kicked, write your own kick command.

**Comment by DelxHQ** [comment]
I agree with @geNAZt. If the administrator wants to have this feature, they should use a plugin to do it.

**Pull request closed without merging**
